INFO     logger:yaml_util.py:24 缓存数据读取成功{'token': 'a46328f58a48cfb5b844798a2c6d59e5'}
ERROR    logger:requests_util.py:34 【绑定上级】接口请求异常，响应体：{'status': 500, 'msg': '已经存在上级', 'data': []}
ERROR    logger:requests_util.py:65 【绑定上级】接口，断言：msg=OK，断言失败。实际值为：已经存在上级